# Overview:

# We have already detected the faces using haarscades)(done)

    -1.Store the face information into numpy array.

    -2. Flatten the largest face image and save in numpy array.

    -3. Repeate the above for multiple people to generate training data and
    store them all in the "data" file which having extension ".npy".



In [1]:
import cv2
import numpy as np
cap=cv2.VideoCapture(0)

#face detection
face_cascade=cv2.CascadeClassifier("haarcascade_frontalface_alt.xml")

while True:
    ret,frame=cap.read()
    
    if ret==False:
        continue
    faces=face_cascade.detectMultiScale(frame,1.3,5)
    print(faces)
    
    for face in faces:
        x,y,w,h=face
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,255),2)
    
    cv2.imshow("Frame",frame)
    
    key_pressed=cv2.waitKey(1) & 0xFF
    if key_pressed == ord('q'):
        break
    
cap.release()
cv2.destroyAllWindows()


# In the output we are geting the Frame dimension ,along with the online vedion stream
    

[[244 132 163 163]]
[[244 119 169 169]]
()
()
()
()
[[252 120 170 170]]
()
[[251 126 163 163]]
[[251 124 163 163]]
[[251 124 163 163]]
[[249 124 170 170]]
[[249 124 170 170]]
[[250 121 168 168]]
[[254 123 163 163]]
[[254 123 163 163]]
[[255 128 163 163]]
[[255 118 173 173]]
[[255 118 173 173]]
[[253 119 173 173]]
[[258 121 170 170]]
[[258 121 170 170]]
[[258 120 171 171]]
[[257 118 173 173]]
[[257 118 173 173]]
[[258 115 177 177]]
[[258 115 177 177]]
()
[[258 118 175 175]]
[[258 118 175 175]]
()
[[256 114 181 181]]
[[259 115 178 178]]
[[259 115 178 178]]
[[254 114 188 188]]
[[260 120 171 171]]
[[264 120 165 165]]
[[259 117 177 177]]
[[260 116 177 177]]
[[267 122 157 157]]
[[268 122 157 157]]
[[268 122 157 157]]
[[266 122 163 163]]
[[259 116 175 175]]
()
[[260 120 171 171]]
[[258 118 171 171]]
()
()
[[264 119 164 164]]
[[261 119 170 170]]
()
()
[[262 119 170 170]]
[[260 118 175 175]]
[[264 121 171 171]]
[[262 119 171 171]]
()
[[266 120 170 170]]
[[266 120 170 170]]
[[268 125 163 163]]
[

In [2]:

import numpy as np
cap=cv2.VideoCapture(0)

#face detection
face_cascade=cv2.CascadeClassifier("haarcascade_frontalface_alt.xml")
skip=0
face_data=[]
dataset_path='./data/'
file_name=input("Enter the name of the person : ")

while True:
    ret,frame=cap.read()
    
    if ret==False:
        continue
    
    gray_frame=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    
    faces=face_cascade.detectMultiScale(frame,1.3,5)
    faces=sorted(faces,key=lambda f:f[2]*f[3])
    
    #pick the last face( because it is the larges face acc to area(f(2) * f(3))
    for face in faces[-1:]:
        x,y,w,h=face
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,255),2)
        
        #extract ( crop the required face): region of interst
        offset=10
        face_section=frame[y-offset:y+h+offset,x-offset:x+w+offset]
        face_section=cv2.resize(face_section,(100,100))
        skip+=1
        if skip%10==0:
            face_data.append(face_section)
            print(len(face_data))
        
        
    cv2.imshow("Frame",frame)
    #cv2.imshow("Face section",face_section)
    #stor every 10 face
   
   # cv2.imshow("face section",face_section)

    key_pressed=cv2.waitKey(1) & 0xFF
    if key_pressed == ord('q'):
        break
        
        
#convert our face list arrray into nupy array
face_data=np.asarray(face_data)
face_data=face_data.reshape((face_data.shape[0],-1))
print(face_data.shape)


# save this data into file system

np.save(dataset_path+file_name+'.npy',face_data)
print("Data successfully save at"+dataset_path+file_name+'.npy')

cap.release()
cv2.destroyAllWindows()



Enter the name of the person : FIROZ THakur
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
(17, 30000)
Data successfully save at./data/FIROZ THakur.npy


# The previous says that 17 frame of the face have been saved in the file Firoz THakur.npy